Updated capstone-sys dependency
    Updating git repository `https://github.com/capstone-rust/capstone-rs`
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching package named `capstone-sys` found (required by `capstone`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.3.0
versions found: 0.4.0, 0.2.0, 0.1.0